name: picowebsite
description: "A Pico website built with Flutter to send commands to pico to control robot movements."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/robot.png"

  web:
    generate: true
    image_path: "assets/icon/robot.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

  windows:
    generate: true
    image_path: "assets/icon/robot.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/icon/robot.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/robot.png